language: cpp
compiler: gcc
dist: xenial

addons:
  apt:
    packages:
      - libibverbs-dev
      - libibmad-dev
      - libibumad-dev
      - libibnetdisc-dev
      - libopensm-dev

stages:
  - name: build

jobs:
  include:
    - stage: build
      script: ./build.sh

before_deploy: tar -cf ib-scanner-${TRAVIS_TAG}.tar -C build/ ar/libcurses.a bin/scanner bin/window-test

deploy:
  provider: releases
  api_key: ${ACCESS_TOKEN}
  file: ib-scanner-${TRAVIS_TAG}.tar
  skip_cleanup: true
  overwrite: true
  on:
    repo: hhu-bsinfo/ib-scanner
    branch: master
    tags: true
